### ISSUE TITLE
presentation_displays:processDebugManifest

### ISSUE THREAD

**Issue by shakirpa** [VNAPNIC/presentation-displays#13]
Thanks a lot for such a wonderful package, but i am having some problem as follows

**Describe the bug**
Launching lib\main.dart on rk3288 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':presentation_displays:processDebugManifest'.
> Failed to calculate the value of task ':presentation_displays:processDebugManifest' property 'packageOverride'.
   > Failed to query the value of property 'applicationId'.
      > Manifest file does not exist: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\presentation_displays-0.2.1\android\src\main\AndroidManifest.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Exception: Gradle task assembleDebug failed with exit code 1

**To Reproduce**
1. Create the basic Flutter demo project 
2. flutter pub add presentation_displays
3. flutter pub get
4. remove entire code from the main.dart
5. copy paste the example code in  presentation-displays/example/lib/main.dart 
6. See error

**Smartphone (please complete the following information):**
 - Device: [rk3288 pos]
 - OS: [Android8.1]

May I know whats wrong I am doing !!?

**Comment by shakirpa** [comment]
Fixed it by copying the android\src\main\AndroidManifest.xml from the github to  C:\src\flutter.pub-cache\hosted\pub.dartlang.org\presentation_displays-0.2.1\android\src\main

**Comment by victorshx** [comment]
> 
> 
> Fixed it by copying the android\src\main\AndroidManifest.xml from the github to C:\src\flutter.pub-cache\hosted\pub.dartlang.org\presentation_displays-0.2.1\android\src\main

You can upgrade `presentation_displays`'s build gradle version to 4.1.0 in `build.gradle` instead.
