### ISSUE TITLE
Implement with GetX Framework

### ISSUE THREAD

**Issue by FigueiredoStable** [VNAPNIC/presentation-displays#17]
Hello, i tried to use this package but the project is based on GetX in case, it encapsulates the MaterialPageRoute and broken the entire app when a use the second screen.

Exist a one way to implement this package with GetX?

**Comment by businesstimch** [comment]
Any solution yet? It looks like it doesn't onGenerateRoute function in 'GetMaterialApp'. Please let us know if there is any solution.

**Comment by businesstimch** [comment]
I think I found a solution.
In my case, I executed 'displayManager.showSecondaryDisplay()' before GetMaterialApp (contains onGenerateRoute method) widget is initialized. Cheers!

**Comment by SpolusApps** [comment]
@businesstimch may you show a example? please.

**Comment by saupz** [comment]
any solution? 

> I think I found a solution. In my case, I executed 'displayManager.showSecondaryDisplay()' before GetMaterialApp (contains onGenerateRoute method) widget is initialized. Cheers!

please share an example code? i tried in my code but it failed..

**Comment by saupz** [comment]
@businesstimch  may you share an example?

**Comment by denisrudnei** [comment]
```
try {
 displayManager.showSecondaryDisplay(
   displayId: 1,
   routerName: Routes.SUNMI_INICIAL_PAGE,
 );
} catch(e) {
 // Do nothing
}

return GetMaterialApp(
    debugShowCheckedModeBanner: false,
    getPages: AppPages.routes,
....
```
