### ISSUE TITLE
Secondary Display is making the main display hang and crashes the app

### ISSUE THREAD

**Issue by WaqarTossdown** [VNAPNIC/presentation-displays#41]
I have integrated the presentation display plugin in my flutter app which is running on POS machine. The issue i am facing right now is i have performed the functionality of presentation display upon the items added to the cart but consistently adding data from the main display to secondary display makes the app hang and crash.

**To Reproduce**
1. Integrate the flutter plugin
2. Add data from multiple clicks 
3. This will hang the main display and make the app crash

**Expected behavior**
I expected that the data will transfer smoothly and work fine but is not happening

**Desktop (please complete the following information):**
 - OS: Android
 - Version 11 to 13

**Smartphone (please complete the following information):**
 - Device: Android POS
 - OS: Android 11 to 13

**Comment by helloFarrukh** [comment]
@VNAPNIC can you please share a solution for this?

**Comment by helloFarrukh** [comment]
@WaqarTossdown 

I have recreated the issue, the issue occurs due to calling the "showSecondaryDisplay" method frequently.

Calling this method only once at the start of the application resolved the issue.

`displayManager.showSecondaryDisplay`
