### ISSUE TITLE
Second Screen Functionality Issue on IMIN D4-504 Pro Device

### ISSUE THREAD

**Issue by abdielLopezpy** [VNAPNIC/presentation-displays#46]
Problem Description:
The functionality of the second screen is not working correctly in release mode on the IMIN D4-504 Pro device.

Steps to Reproduce:

Build and run the Flutter project in release mode on the IMIN D4-504 Pro device.
Observe that the second screen does not display the expected information correctly.
Expected Behavior:
The second screen should function correctly in release mode on the IMIN D4-504 Pro device, similar to how it behaves in debug mode.

Additional Information:

The presentation_displays library is used to support the functionality of running the application on two screens, either through an HDMI or wireless connection.
The sample application has been tested on Android devices and works correctly in debug mode.
Let me know if you need further assistance!

**Comment by patelnirav48** [comment]
@abdielLopezpy Is this working fine now?

**Comment by patelnirav48** [comment]
@VNAPNIC We're using iMin secondary display and with release APK not working. could you please help what could be the issue?
