### ISSUE TITLE
Touchscreen stops responding

### ISSUE THREAD

**Issue by dan8551** [VNAPNIC/presentation-displays#48]
**Describe the bug**
When using the example, after selecting screen ID and pressing "show presentation" the touchscreen stops responding to any click. RustDesk can still be used for pressing buttons including "hide presentation" when the touchscreen starts working again.

**To Reproduce**
1. Enter index to share screen
2. Click on "Show Presentations"
3. Try clicking anywhere on screen, including android buttons

**Expected behavior**
Touch screen should still respond during presentation mode

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: POS with 2 screens (Rockchip RK3568 EVB1 DDR4 V10 Board)
 - OS: Android 11

**Comment by saunptit97** [comment]
I have same issue with you. Did you resolve this issue? @dan8551
