### ISSUE TITLE
show if idle display

### ISSUE THREAD

**Issue by saleh-aleid** [VNAPNIC/presentation-displays#5]
many thanks for your great work
now i have a question or idea if the mean screen it is idle (no one it is work on it) i want display for example a message or some of images
how i can do it

**Comment by VNAPNIC** [comment]
You can use the callback of the widget SecondaryDisplay to display the look you want.
if there is no data you can display an empty widget.
Or u can wrap the stack widget so that another widget is overlapped.
Like that.

```
bool isCanShowSecondaryDisplay = false;

Stack(
  children: <Widget>[
   econdaryDisplay(
      callback: (argument) {
        setState(() {
          value = argument;
        });
      },
      child: Center(
        child: Text(value),
      ),
    ),
   if( isCanShowSecondaryDisplay )
      MyWidget()
  ]
)

```

**Comment by saleh-aleid** [comment]
thank you for your response but my idea it is like screensaver on windows or mac

**Comment by saleh-aleid** [comment]
you are a genius
i try to do your code it is work good
now my friend i have issue if you can help me please
how i can make the usb scanner reader read a barcode without focus on textfield
